comment: off

codecov:
  require_ci_to_pass: no
  notify: 
    wait_for_ci: no

ignore:
  - "pkg/git"

coverage:
  status:
    patch:
      default:
        informational: true
    project:
      default:
        target: auto
        threshold: 1%
        removed_code_behavior: adjust_base
        if_ci_failed: success
      required:
        threshold: 2%