{
 "title": "Component Building (simple build)",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Simple builds total count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redhat_appstudio_buildservice_simple_build_pipeline_creation_time_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Simple build submission time distribution",
   "type": "bargauge",
   "description": "Each bar shows how many simple build pipeline runs were prepared in the time range. For example, \"15\" bar shows the number of simple build pipeline runs preparations that took from 10 to 15 seconds.",
   "gridPos": { "h": 11, "w": 12, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "redhat_appstudio_buildservice_simple_build_pipeline_creation_time_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Increase of simple builds on timeline",
   "type": "heatmap",
   "description": "Shows increase of simple build pipeline runs in each time category over time",
   "gridPos": { "h": 12, "w": 17, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(increase(redhat_appstudio_buildservice_simple_build_pipeline_creation_time_bucket[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Simple build pipeline run submission average time on timeline",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "rate(redhat_appstudio_buildservice_simple_build_pipeline_creation_time_sum[$__rate_interval])/rate(redhat_appstudio_buildservice_simple_build_pipeline_creation_time_count[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}