{
 "title": "Component Onboarding (Pipelines-as-Code)",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Pipelines as Code provisions total count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redhat_appstudio_buildservice_PaC_configuration_time_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pipelines as Code provisions time distribution",
   "type": "bargauge",
   "description": "Each bar shows how many repositories were provisioned in the time range. For example, \"15\" bar shows the number of git repository provisions that took from 10 to 15 seconds.",
   "gridPos": { "h": 11, "w": 12, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "redhat_appstudio_buildservice_PaC_configuration_time_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Increase of Pipelines as Code provisions on timeline",
   "type": "heatmap",
   "description": "Shows increase of Pipelines as Code provisions in each time category over time",
   "gridPos": { "h": 12, "w": 17, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(increase(redhat_appstudio_buildservice_PaC_configuration_time_bucket[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Pipelines as Code provisions average time on timeline",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "rate(redhat_appstudio_buildservice_PaC_configuration_time_sum[$__rate_interval])/rate(redhat_appstudio_buildservice_PaC_configuration_time_count[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}