{
 "title": "Component Onboarding (initial build)",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Initial builds total count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redhat_appstudio_buildservice_initial_build_pipeline_creation_time_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Initial build submition time",
   "type": "bargauge",
   "description": "Time spent from the Component creation till initial build pipeline run creation.\nEach bar shows how many pipeline runs were submitted in the time range. For example, number on \"15\" bar shows the number of initial build pipeline runs preparation of which took from 10 to 15 seconds.",
   "gridPos": { "h": 11, "w": 12, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "redhat_appstudio_buildservice_initial_build_pipeline_creation_time_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Initial builds on timeline",
   "type": "heatmap",
   "description": "Shows increase of initial build pipeline runs in each time category over time",
   "gridPos": { "h": 12, "w": 17, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(increase(redhat_appstudio_buildservice_initial_build_pipeline_creation_time_bucket[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Initial build pipeline run submition average time on timeline",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "rate(redhat_appstudio_buildservice_initial_build_pipeline_creation_time_sum[$__rate_interval])/rate(redhat_appstudio_buildservice_initial_build_pipeline_creation_time_count[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}