# permissions for end users to view BuildPipelineSelectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: BuildPipelineSelector-viewer-role
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - BuildPipelineSelectors
  verbs:
  - get
  - list
  - watch
