# permissions for end users to edit BuildPipelineSelectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: BuildPipelineSelector-editor-role
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - BuildPipelineSelectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
