apiVersion: appstudio.redhat.com/v1alpha1
kind: BuildPipelineSelector
metadata:
  name: build-pipeline-selector-sample
spec:
  selectors:
    - name: Docker build
      pipelineRef:
        name: docker-build
        bundle: build-bundle
      pipelineParams:
        - name: engine
          value: buildah
      when:
        dockerfile: true
    - name: Java
      pipelineRef:
        name: java-builder
        bundle: build-bundle
      when:
        language: java
    - name: NodeJS
      pipelineRef:
        name: nodejs-builder
        bundle: build-bundle
      when:
        language: nodejs,node
    - name: Python
      pipelineRef:
        name: python-builder
        bundle: build-bundle
      when:
        language: python
    - name: Fallback
      pipelineRef:
        name: generic-builder
        bundle: build-bundle
