apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-service-on-push
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  params:
    - name: git-url
      value: "{{repo_url}}"
    - name: revision
      value: "{{revision}}"
    - name: output-image
      value: 'quay.io/konflux-ci/build-service:{{revision}}'
    - name: infra-deployment-update-script
      value: |
        sed -i -e 's|\(https://github.com/konflux-ci/build-service/.*?ref=\)\(.*\)|\1{{ revision }}|' -e 's/\(newTag: \).*/\1{{ revision }}/' components/build-service/development/kustomization.yaml
        sed -i -e 's|\(https://github.com/konflux-ci/build-service/.*?ref=\)\(.*\)|\1{{ revision }}|' -e 's/\(newTag: \).*/\1{{ revision }}/' components/build-service/staging/base/kustomization.yaml
    - name: slack-webhook-notification-team
      value: build
  pipelineRef:
    params:
      - name: bundle
        value: >-
          quay.io/redhat-appstudio-tekton-catalog/pipeline-core-services-docker-build:latest
      - name: name
        value: docker-build
      - name: kind
        value: Pipeline
    resolver: bundles
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
