apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-service-pull-request
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  pipelineSpec:
    tasks:
      - name: foo
        taskSpec:
          results:
            - name: big
          steps:
            - name: step-0
              image: registry.access.redhat.com/ubi9/ubi-minimal:latest
              script: |
                # 4000 * 'x'
                printf 'x%.0s' {1..4000} >$(results.big.path)

            - name: step-1
              image: registry.access.redhat.com/ubi9/ubi-minimal:latest
              script: |
                rm $(results.big.path)
