---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: konflux-e2e-tests
spec:
  description: |-
    This pipeline automates the process of running end-to-end tests for Konflux
    using a Kind cluster running on AWS cluster. The pipeline provisions
    the Kind cluster, installs Konflux using the konflux-ci repository scripts, runs the tests, collects artifacts,
    and finally deprovisions the Kind cluster.
  params:
    - name: SNAPSHOT
      description: 'The JSON string representing the snapshot of the application under test.'
      default: '{"components": [{"name":"test-app", "containerImage": "quay.io/example/repo:latest"}]}'
      type: string
    - name: konflux-test-infra-secret
      description: The name of secret where testing infrastructures credentials are stored.
      default: "konflux-test-infra"
      type: string
    - name: oci-container-repo
      default: 'quay.io/konflux-test-storage/konflux-team/build-service'
      description: The OCI container used to store all test artifacts.
    - name: artifact-browser-url
      description: "URL to the artifact browser deployment. If provided, a link will be added to PR comments."
      default: ""
      type: string
  tasks:
    - name: test-metadata
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-ci/tekton-integration-catalog.git
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/test-metadata/0.4/test-metadata.yaml
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
        - name: test-name
          value: $(context.pipelineRun.name)
