apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-reader
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: metrics-reader
  name: metrics-reader
type: kubernetes.io/service-account-token
